# Introduction to NumPy


The learning objectives of this section are:

* Understand advantages of vectorised code using NumPy
* Create NumPy arrays
* Multi dimentional array
* Inspect the structure and content of arrays
* Subset, slice, index and iterate through arrays
* Compare computation times in NumPy and standard Python lists

In [1]:
import numpy as np

In [2]:
#Create 1D array
lis = [1,2,3,4,5]
array_1d = np.array(lis)

In [3]:
array_1d

array([1, 2, 3, 4, 5])

In [4]:
type(array_1d)

numpy.ndarray

In [10]:
#Create 2D array
#Create 1D array
lis1 = [1,2,3,4,5]
lis2 = [6,7,8,9,10]
array_2d = np.array([lis1, lis2])

In [11]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
#1 is ref as cols
#0 is ref as rows

In [17]:
lis_1 = [1,2,3,5]
lis_2 = [1,2,4,5]

#list way
product = list(map(lambda x,y: x*y, lis_1, lis_2))
print(product)

#numpy
lis_1 = np.array(lis_1)
lis_2 = np.array(lis_2)
print(lis_1*lis_2)

[1, 4, 12, 25]
[ 1  4 12 25]


In [19]:
#list way
li1 = [i**2 for i in lis_1]
print(li1)

#numpy way
print(lis_1**2)

[1, 4, 9, 25]
[ 1  4  9 25]


In [23]:
tup = (1,2,3,4,5)
lis = [1,3,45,5,6]

tup_array = np.array(tup)
lis_array = np.array(lis)

In [25]:
print(type(tup_array))
print(type(lis_array))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [26]:
#Builtin fn of numpy

In [ ]:
np.zeros
np.ones
np.arange
np.random
np.linspace

In [27]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
   

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros(((5,5)))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
np.ones((5,3), dtype=np.int)

C:\Users\ramsu\AppData\Local\Temp\ipykernel_15672\290869102.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((5,3), dtype=np.int)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
#Random
np.random.random([2,4])

array([[0.17195346, 0.50250371, 0.77267219, 0.70015114],
       [0.31103599, 0.56120456, 0.25040958, 0.50509149]])

In [41]:
np.arange(5, 100)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [42]:
np.arange(5, 100, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [43]:
np.linspace(10, 20, 50)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [ ]:
#np.full
#np.tile
#np.eye

In [44]:
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [45]:
np.full((4,3), 6)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
arr = [1,2,3]
tile = np.tile(arr, 3)

In [52]:
tile

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
np.tile(arr, (3,4))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [55]:
np.tile(arr, (2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [68]:
random_arraay = np.random.random((1000,100))
random_arraay

array([[0.07261172, 0.06199886, 0.8952147 , ..., 0.25157591, 0.29166515,
        0.18111948],
       [0.13392172, 0.87398306, 0.62854613, ..., 0.74525565, 0.73948881,
        0.85489859],
       [0.05457275, 0.07065335, 0.67616161, ..., 0.73215679, 0.29349474,
        0.12818742],
       ...,
       [0.57612683, 0.53245406, 0.50285196, ..., 0.45504612, 0.17134713,
        0.15138779],
       [0.26882006, 0.05517358, 0.9982604 , ..., 0.5040136 , 0.00951227,
        0.4377426 ],
       [0.70789569, 0.53942743, 0.99364594, ..., 0.45061581, 0.31522324,
        0.85974231]])

In [58]:
print("Shape ", random_arraay.shape)
print("Dim ", random_arraay.ndim)
print("Dtypes ", random_arraay.dtype)
print("Item Size ", random_arraay.itemsize)

Shape  (1000, 100)
Dim  2
Dtypes  float64
Item Size  8


In [61]:
lis_array.itemsize

4

In [62]:
lis_array

array([ 1,  3, 45,  5,  6])

In [ ]:
#3d

In [94]:
arr_3d = np.arange(24)

In [95]:
arr_3d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [97]:
arr_3dd = arr_3d.reshape(2,3,4)

In [98]:
arr_3dd.ndim

3

In [ ]:
#Slicing

In [100]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [103]:
print(arr[1])

1


In [104]:
print(arr[5:])

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [105]:
print(arr[:5])

[0 1 2 3 4]


In [106]:
print(arr[5:10])

[5 6 7 8 9]


In [119]:
arr = np.array([[1,2,3],[1,2,3],[3,2,1]])

In [120]:
arr

array([[1, 2, 3],
       [1, 2, 3],
       [3, 2, 1]])

In [121]:
arr.ndim

2

In [130]:
print(arr[1,2])

3


In [131]:
print(arr[:, 2])

[3 3 1]


In [132]:
print(arr[:, 1])

[2 2 2]


In [134]:
print(arr[1, :])

[1 2 3]


In [135]:
import time

In [150]:
list_1 = [i for i in range(10000000)]
list_2 = [j**2 for j in range(10000000)]

In [151]:
#list way
t0 = time.time()
prodct_list = list(map(lambda x,y: x*y, list_1, list_2))
t1 = time.time()
time_took = t1-t0
print(time_took)

2.17600679397583


In [152]:
#numpy way
a = np.array(list_1)
b = np.array(list_2)
t0 = time.time()
prodct_list_1 = a*b
t1 = time.time()
time_took1 = t1-t0
print(time_took1)

0.04785966873168945


In [153]:
time_took/time_took1

45.46639898773525

In [ ]:
#Stacking
#Manipulation of Array
#Some Linear Algebra Operations

In [1]:
import numpy as np

In [4]:
array = np.arange(0,12)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
array_reshape = array.reshape(3,4)
array_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
array_reshape1 = array_reshape.reshape(2,6)
array_reshape1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
array_reshape1 = array_reshape.reshape(3,6)
array_reshape1

ValueError: cannot reshape array of size 12 into shape (3,6)

In [10]:
array_reshape1 = array_reshape.reshape(4,-1)
array_reshape1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
#Transpose
array_reshape1.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [ ]:
#Stacking techniques

In [14]:
array1 = np.arange(12).reshape(3,4)
array2 = np.arange(20).reshape(5,4)

print(array1)
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
#for V stack : no of columns should be same
#for h stack : no. of rows should be same

In [17]:
np.vstack((array1, array2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
#Mathematical operation

In [54]:
a = np.arange(1, 20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [19]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]


In [20]:
print(np.cos(a))
print(np.exp(a))
print(np.log(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.77258872 2.83321334 2.89037176
 2.94443898]


In [21]:
#Vectorization

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [44]:
#List way
lis = [x/(x+1) for x in a]
print(lis)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [67]:
#Vector way
k = lambda x: x/(x+1)
f1 = np.vectorize(k)

In [68]:
f1(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [ ]:
#Basic algebra operation

In [85]:
a = np.arange(11,20).reshape(3,3)
b = np.arange(1,13).reshape(3,4)

print(a)
print(b)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [86]:
np.linalg.inv(a)

array([[ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-2.81474977e+14,  5.62949953e+14, -2.81474977e+14],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14]])

In [87]:
np.linalg.det(a)

-2.131628207280298e-14

In [88]:
np.linalg.eig(a)

(array([ 4.53965063e+01, -3.96506284e-01, -5.74446157e-17]),
 array([[-0.45694089, -0.7371869 ,  0.40824829],
        [-0.56993163, -0.03110723, -0.81649658],
        [-0.68292237,  0.67497245,  0.40824829]]))

In [90]:
help(np.linalg.inv)

Help on function inv in module numpy.linalg:

inv(a)
    Compute the (multiplicative) inverse of a matrix.
    
    Given a square matrix `a`, return the matrix `ainv` satisfying
    ``dot(a, ainv) = dot(ainv, a) = eye(a.shape[0])``.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Matrix to be inverted.
    
    Returns
    -------
    ainv : (..., M, M) ndarray or matrix
        (Multiplicative) inverse of the matrix `a`.
    
    Raises
    ------
    LinAlgError
        If `a` is not square or inversion fails.
    
    See Also
    --------
    scipy.linalg.inv : Similar function in SciPy.
    
    Notes
    -----
    
    .. versionadded:: 1.8.0
    
    Broadcasting rules apply, see the `numpy.linalg` documentation for
    details.
    
    Examples
    --------
    >>> from numpy.linalg import inv
    >>> a = np.array([[1., 2.], [3., 4.]])
    >>> ainv = inv(a)
    >>> np.allclose(np.dot(a, ainv), np.eye(2))
    True
    >>> np.allclose(np.dot(ainv, a), 

In [89]:
np.linalg.inv(b)

LinAlgError: Last 2 dimensions of the array must be square

In [91]:
np.dot(a, b)

array([[188, 224, 260, 296],
       [233, 278, 323, 368],
       [278, 332, 386, 440]])